---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: nginx-spot
spec:
  consolidation:
    enabled: true
  providerRef:
    name: nginx-spot
  labels:
    targetNodeType: karpenter-nginx
    type: spot
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
      - t3a
      - t3
    - key: karpenter.k8s.aws/instance-cpu
      operator: Lt
      values:
      - "5"
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn # avoid instance-size too small
      values:
      - nano
      - micro
    - key: capacity-spread
      operator: In
      values:
      - "1"
      - "2"

---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: nginx-ondemand
spec:
  consolidation:
    enabled: true
  providerRef:
    name: nginx-ondemand
  labels:
    targetNodeType: karpenter-nginx
    type: on-demand
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
      - t3a
      - t3
    - key: karpenter.k8s.aws/instance-cpu
      operator: Lt
      values:
      - "5"
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn # avoid instance-size too small
      values:
      - nano
      - micro
    - key: capacity-spread
      operator: In
      values:
      - "3"
      - "4"
      - "5"

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: nginx-spot
spec:
  amiFamily: AL2
  subnetSelector:
    karpenter.sh/discovery: eks-demo
  securityGroupSelector:
    karpenter.sh/discovery: eks-demo

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: nginx-ondemand
spec:
  amiFamily: AL2
  subnetSelector:
    karpenter.sh/discovery: eks-demo
  securityGroupSelector:
    karpenter.sh/discovery: eks-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:stable
        name: nginx
        resources:
          requests:
            cpu: 100m
      nodeSelector:
        targetNodeType: karpenter-nginx
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: nginx
        maxSkew: 1
        topologyKey: capacity-spread
        whenUnsatisfiable: DoNotSchedule
