---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-static-volume
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: http-server
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-html
  volumes:
    - name: nginx-html
      persistentVolumeClaim:
        claimName: pvc-gp3
