# ref: https://karpenter.sh/preview/concepts/nodeclasses/
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: eks-demo
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: eks-demo
  tags:
    karpenter: "true"
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        deleteOnTermination: true
  detailedMonitoring: true
  role: KarpenterNodeRole-eks-demo
