---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: imdsv1
spec:
  amiFamily: AL2
  subnetSelector:
    karpenter.sh/discovery: eks-demo
  securityGroupSelector:
    karpenter.sh/discovery: eks-demo
  tags:
    karpenter: "true"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        deleteOnTermination: true
  detailedMonitoring: true
