# ref: https://karpenter.sh/preview/concepts/nodepools/
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidationPolicy: WhenUnderutilized
    # consolidateAfter: 30s
    expireAfter: 720h0m0s
  limits:
    cpu: 1000
    memory: 1000Gi
  template:
    metadata:
      labels:
        managed-by: karpenter
    spec:
      kubelet: {}
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
        # - spot
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
        # - arm64
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - t3a
        - c5a
        - m5a
        - m6a
      - key: karpenter.k8s.aws/instance-cpu
        operator: Lt
        values:
        - "17" # 16 + 1
      - key: karpenter.k8s.aws/instance-memory
        operator: Lt
        values:
        # - "16385" # 16 * 1024 + 1 (16 GiB)
        # - "32769" # 32 * 1024 + 1 (32 GiB)
        - "65537" # 64 * 1024 + 1 (64 GiB)
      - key: karpenter.k8s.aws/instance-size
        operator: NotIn
        values:
        - nano
        - micro
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
