apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  providerRef:
    name: default
  kubeletConfiguration:
    containerRuntime: containerd
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
    # - spot
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
    # - arm64
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values:
    - t3a
    - c5a
    - m5a
    - m6a
  - key: karpenter.k8s.aws/instance-cpu
    operator: Lt
    values:
    - "17" # 16 + 1
  - key: karpenter.k8s.aws/instance-memory
    operator: Lt
    values:
    # - "16385" # 16 * 1024 + 1 (16 GiB)
    # - "32769" # 32 * 1024 + 1 (32 GiB)
    - "65537" # 64 * 1024 + 1 (64 GiB)
  - key: karpenter.k8s.aws/instance-size
    operator: NotIn # avoid instance-size too small
    values:
    - nano
    - micro
  # ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
